### ISSUE TITLE
Duplicate examples in "How'd You Get Here?"?

### ISSUE THREAD

**Issue by raghubetina** [hotwired/hotwire-native-demo#10]
I've followed the instructions in the [Hotwire Native iOS: Getting Started guide](https://native.hotwired.dev/ios/getting-started), and am playing around with the demo app.

In `Basic Features > Navigate to another page > How'd You Get Here?`, are the last two examples duplicates? They both seem to be showing the same thing (refreshing programmatically with `replace`):

<img width="389" alt="Screenshot 2024-09-29 at 4 12 41 PM" src="https://github.com/user-attachments/assets/d4887a5f-ae6e-4231-bbcc-84a85a983576">

**Comment by leonvogt** [comment]
The outcome of both actions is identical, but the methods used to trigger the page refresh differ:

- The "Refresh" button performs a replace visit by linking to the same page with `data-turbo-action="replace"`, which triggers a Turbo morph.
- The "Refresh programmatically" button calls the JavaScript function `Turbo.session.refresh(document.baseURI)`, which also triggers a Turbo morph.   

```html
<p class="space --bottom-s">This performs a <code>replace</code> visit to the current page, refreshing its content with morphing:</p>
<p><a href="/one" class="button@native" data-turbo-action="replace">Refresh</a></p>

<p class="space --bottom-s">This programatically refreshes the current page, performing a <code>replace</code> visit and refreshing its content with morphing:</p>
<p><a id="refresh" class="button@native" data-turbo-action="replace">Refresh programatically</a></p>

<footer class="text --size-s --color-subtle space --top-xxl">
  Rendered <%- new Date().toLocaleString() %> via Turbo 8
</footer>

<script>
  document.getElementById("refresh").addEventListener("click", () => {
    Turbo.session.refresh(document.baseURI)
  })
</script>
```


I guess the demo just wanna illustrates that both approaches can refresh the page content through morphing, but one uses an HTML anchor link, while the other relies on JavaScript to achieve the same result.

**Comment by jayohms** [comment]
Correct @leonvogt, thanks for the thorough explanation 👍
